import type { ThreatId, TowerId } from '../core/types';

/**
 * Pixel art as source code. Every sprite is a 16x16 character grid plus a
 * palette; '.' is transparent. Nothing binary ships with the game, the art
 * diffs like code, and recolouring a whole family is a one-line change.
 *
 * `bake.ts` validates the grid dimensions at load time, so a miscounted row
 * fails loudly instead of rendering as a subtly clipped sprite.
 */
export interface PixelSprite {
  rows: string[];
  palette: Record<string, string>;
}

export const SPRITE_SIZE = 16;

const s = (palette: Record<string, string>, rows: string[]): PixelSprite => ({ rows, palette });

/* ------------------------------------------------------------------ threats */

export const THREAT_SPRITES: Record<ThreatId, PixelSprite> = {
  virus: s(
    { A: '#12512b', B: '#37d16b', C: '#a7f3c4', D: '#06210f' },
    [
      '................',
      '.......AA.......',
      '...A...AA...A...',
      '....A.ABBA.A....',
      '.....ABBBBA.....',
      '..A.ABBBBBBA.A..',
      '...AABBBBBBAA...',
      'AAAABBBDDBBBAAAA',
      'AAAABBBDDBBBAAAA',
      '...AABBBBBBAA...',
      '..A.ABBBBBBA.A..',
      '.....ABBBBA.....',
      '....A.ABBA.A....',
      '...A...AA...A...',
      '.......AA.......',
      '................',
    ],
  ),

  worm: s(
    { A: '#0b4f52', B: '#22d3ee', C: '#a5f3fc' },
    [
      '................',
      '................',
      '....AAAA........',
      '...ABBBBA.......',
      '..ABBCCBBA......',
      '..ABBCCBBA.AAA..',
      '..ABBBBBBA.ABBA.',
      '...ABBBBA.ABBBBA',
      '....ABBBBAABBBBA',
      '.....ABBBBBBBBA.',
      '......AAABBBBA..',
      '........AAAAA...',
      '................',
      '................',
      '................',
      '................',
    ],
  ),

  phishing: s(
    { A: '#7c2d12', B: '#fb923c', C: '#fed7aa' },
    [
      '................',
      '........AAAA....',
      '........A..A....',
      '...........A....',
      '..AAAAAAAAAA....',
      '..ABBBBBBBBA....',
      '..ABCBBBBCBA....',
      '..ABBCBBCBBA....',
      '..ABBBCCBBBA....',
      '..ABBBBBBBBA....',
      '..AAAAAAAAAA....',
      '................',
      '................',
      '................',
      '................',
      '................',
    ],
  ),

  trojan: s(
    { A: '#4c1d95', B: '#a78bfa', C: '#ddd6fe', D: '#2e1065' },
    [
      '................',
      '................',
      '...AAAAAAAAAA...',
      '...ABBBBBBBBA...',
      '...ABCCBBCCBA...',
      '...ABCCBBCCBA...',
      '...ABBBBBBBBA...',
      '...ABBCCCCBBA...',
      '...ABBCDDCBBA...',
      '...ABBBBBBBBA...',
      '...AAAAAAAAAA...',
      '....A......A....',
      '....A......A....',
      '................',
      '................',
      '................',
    ],
  ),

  ransomware: s(
    { A: '#7f1d1d', B: '#ef4444', C: '#fecaca', D: '#450a0a' },
    [
      '................',
      '.....AAAAAA.....',
      '....AA....AA....',
      '....A......A....',
      '....A......A....',
      '..AAAAAAAAAAAA..',
      '..ABBBBBBBBBBA..',
      '..ABBBBDDBBBBA..',
      '..ABBBDDDDBBBA..',
      '..ABBBBDDBBBBA..',
      '..ABBBBDDBBBBA..',
      '..ABBBBBBBBBBA..',
      '..AAAAAAAAAAAA..',
      '................',
      '................',
      '................',
    ],
  ),

  botnet: s(
    { A: '#831843', B: '#ec4899', C: '#fbcfe8' },
    [
      '................',
      '..CC........CC..',
      '..CC........CC..',
      '....A......A....',
      '.....AAAAAA.....',
      '....ABBBBBBA....',
      '...ABBBCCBBBA...',
      '...ABBCCCCBBA...',
      '...ABBCCCCBBA...',
      '...ABBBCCBBBA...',
      '....ABBBBBBA....',
      '.....AAAAAA.....',
      '....A......A....',
      '..CC........CC..',
      '..CC........CC..',
      '................',
    ],
  ),

  bot: s(
    { A: '#6b21a8', B: '#c084fc', C: '#f3e8ff' },
    [
      '................',
      '................',
      '................',
      '................',
      '.....AAAAAA.....',
      '....ABBBBBBA....',
      '....ABCBBCBA....',
      '....ABBBBBBA....',
      '....ABBCCBBA....',
      '....ABBBBBBA....',
      '.....AAAAAA.....',
      '................',
      '................',
      '................',
      '................',
      '................',
    ],
  ),

  rootkit: s(
    { A: '#334155', B: '#94a3b8', C: '#e2e8f0' },
    [
      '................',
      '................',
      '.....AAAAAA.....',
      '...AABBBBBBAA...',
      '..ABBBBBBBBBBA..',
      '..ABBCCBBCCBBA..',
      '..ABBCCBBCCBBA..',
      '..ABBBBBBBBBBA..',
      '..ABBBBCCBBBBA..',
      '..ABBBBBBBBBBA..',
      '..ABBBBBBBBBBA..',
      '..ABABBABBABBA..',
      '..AA.AA.AA.AAA..',
      '................',
      '................',
      '................',
    ],
  ),

  cryptominer: s(
    { A: '#78350f', B: '#f59e0b', C: '#fde68a', D: '#451a03' },
    [
      '................',
      '..........AA....',
      '.........AA.....',
      '....AAAAAAAA....',
      '...ABBBBBBBBA...',
      '..ABBCCBBCCBBA..',
      '..ABBCCBBCCBBA..',
      '..ABBBBBBBBBBA..',
      '..ABDDBBBBDDBA..',
      '..ABBBBBBBBBBA..',
      '...ABBBBBBBBA...',
      '....AAAAAAAA....',
      '....A..AA..A....',
      '................',
      '................',
      '................',
    ],
  ),

  ddos: s(
    { A: '#164e63', B: '#06b6d4', C: '#cffafe' },
    [
      '................',
      '................',
      '................',
      '................',
      '................',
      '......AAAA......',
      '.....ABBBBA.....',
      '.....ABCCBA.....',
      '.....ABCCBA.....',
      '.....ABBBBA.....',
      '......AAAA......',
      '................',
      '................',
      '................',
      '................',
      '................',
    ],
  ),

  tunnel: s(
    { A: '#1e3a8a', B: '#60a5fa', C: '#bfdbfe', D: '#172554' },
    [
      '................',
      '................',
      '................',
      '....AAAAAAAA....',
      '...ABBBBBBBBA...',
      '..ABBCCCCCCBBA..',
      '.ABBCBBBBBBCBBA.',
      '.ABBCBDDDDBCBBA.',
      '.ABBCBDDDDBCBBA.',
      '.ABBCBBBBBBCBBA.',
      '..ABBCCCCCCBBA..',
      '...ABBBBBBBBA...',
      '....AAAAAAAA....',
      '................',
      '................',
      '................',
    ],
  ),

  logicbomb: s(
    { A: '#3f3f46', B: '#a1a1aa', C: '#fb7185', D: '#18181b' },
    [
      '................',
      '............CC..',
      '...........C....',
      '..........C.....',
      '.......AAAA.....',
      '.....AAABBBA....',
      '....ABBBBBBBA...',
      '...ABBDDBBBBBA..',
      '...ABBDDBBBBBA..',
      '...ABBBBBBBBBA..',
      '....ABBBBBBBA...',
      '.....AAAAAAA....',
      '................',
      '................',
      '................',
      '................',
    ],
  ),

  apt: s(
    { A: '#581c87', B: '#9333ea', C: '#e9d5ff', D: '#1e1b4b' },
    [
      '................',
      '......AAAA......',
      '....AABBBBAA....',
      '...ABBBBBBBBA...',
      '..ABBBBBBBBBBA..',
      '..ABBCCCCCCBBA..',
      '.ABBCCCDDCCCBBA.',
      '.ABBCCDDDDCCBBA.',
      '.ABBCCCDDCCCBBA.',
      '..ABBCCCCCCBBA..',
      '..ABBBBBBBBBBA..',
      '...ABBBBBBBBA...',
      '....AABBBBAA....',
      '......AAAA......',
      '................',
      '................',
    ],
  ),

  zeroday: s(
    { A: '#450a0a', B: '#dc2626', C: '#fca5a5', D: '#1c0505' },
    [
      '................',
      '....AAAAAAAA....',
      '..AABBBBBBBBAA..',
      '.ABBBBBBBBBBBBA.',
      '.ABBBBBBBBBBBBA.',
      '.ABDDBBBBBBDDBA.',
      '.ABDDDBBBBDDDBA.',
      '.ABDDBBBBBBDDBA.',
      '.ABBBBBDDBBBBBA.',
      '.ABBBBBDDBBBBBA.',
      '.ABBBBBBBBBBBBA.',
      '..ABDBDBDBDBDA..',
      '..ABDBDBDBDBDA..',
      '...AAAAAAAAAA...',
      '................',
      '................',
    ],
  ),
};

/* ------------------------------------------------------------------- towers */

export const TOWER_SPRITES: Record<TowerId, PixelSprite> = {
  firewall: s(
    { A: '#7f1d1d', B: '#ef4444', C: '#fb923c', D: '#fde68a' },
    [
      '................',
      '....CC....CC....',
      '...CDDC..CDDC...',
      '....CC....CC....',
      '..AAAAAAAAAAAA..',
      '..ABBBABBBABBBA.',
      '..AAAAAAAAAAAA..',
      '..ABABBBABBBABA.',
      '..AAAAAAAAAAAA..',
      '..ABBBABBBABBBA.',
      '..AAAAAAAAAAAA..',
      '..ABABBBABBBABA.',
      '..AAAAAAAAAAAA..',
      '................',
      '................',
      '................',
    ],
  ),

  antivirus: s(
    { A: '#14532d', B: '#22c55e', C: '#bbf7d0' },
    [
      '................',
      '...AAAAAAAAAA...',
      '..ABBBBBBBBBBA..',
      '..ABBBBBBBBCBA..',
      '..ABBBBBBBCBBA..',
      '..ABBCBBBCBBBA..',
      '..ABBBCBCBBBBA..',
      '..ABBBBCBBBBBA..',
      '..ABBBBBBBBBBA..',
      '...ABBBBBBBBA...',
      '....ABBBBBBA....',
      '.....ABBBBA.....',
      '......ABBA......',
      '.......AA.......',
      '................',
      '................',
    ],
  ),

  ids: s(
    { A: '#4c1d95', B: '#a78bfa', C: '#ddd6fe', D: '#c4b5fd' },
    [
      '................',
      '.......CC.......',
      '......CDDC......',
      '.....CDDDDC.....',
      '....CDDDDDDC....',
      '................',
      '..AAAAAAAAAAAA..',
      '..ABBBBBBBBBBA..',
      '..ABCCBBBBCCBA..',
      '..ABBBBBBBBBBA..',
      '..ABBBBCCBBBBA..',
      '..ABBBBBBBBBBA..',
      '..AAAAAAAAAAAA..',
      '................',
      '................',
      '................',
    ],
  ),

  encryption: s(
    { A: '#0c4a6e', B: '#38bdf8', C: '#bae6fd', D: '#082f49' },
    [
      '................',
      '................',
      '.....AAAAAA.....',
      '....ABBBBBBA....',
      '...ABBCCCCBBA...',
      '...ABCDDDDCBA...',
      '...ABCDDDDCBA...',
      '...ABBCCCCBBA...',
      '....ABBBBBBA....',
      '.....ABBBBA.....',
      '......ABBA......',
      '......ABBA......',
      '....AAABBAAA....',
      '....A......A....',
      '................',
      '................',
    ],
  ),

  honeypot: s(
    { A: '#78350f', B: '#f59e0b', C: '#fcd34d' },
    [
      '................',
      '................',
      '...AAAAAAAAAA...',
      '...ACCCCCCCCA...',
      '...AAAAAAAAAA...',
      '....ABBBBBBA....',
      '....ABCBBCBA....',
      '....ABBBBBBA....',
      '....ABBCCBBA....',
      '....ABBBBBBA....',
      '....ABBBBBBA....',
      '.....AAAAAA.....',
      '......C..C......',
      '......C..C......',
      '................',
      '................',
    ],
  ),

  soc: s(
    { A: '#7c2d12', B: '#f97316', C: '#fed7aa' },
    [
      '................',
      '..AAAAAAAAAAAA..',
      '..ABBBBBBBBBBA..',
      '..ABCCBCBBCCBA..',
      '..ABBBBBBBBBBA..',
      '..ABCBCCBCBCBA..',
      '..ABBBBBBBBBBA..',
      '..ABCCBCCBCCBA..',
      '..ABBBBBBBBBBA..',
      '..AAAAAAAAAAAA..',
      '......AAAA......',
      '......AAAA......',
      '....AAAAAAAA....',
      '................',
      '................',
      '................',
    ],
  ),

  sentinel: s(
    { A: '#713f12', B: '#facc15', C: '#fef08a', D: '#422006' },
    [
      '................',
      '....AAAAAAAA....',
      '..AACCCCCCCCAA..',
      '.ACCCDDDDDDCCCA.',
      '.ACCDDDDDDDDCCA.',
      '.ACCDDDAADDDCCA.',
      '.ACCDDDAADDDCCA.',
      '.ACCDDDDDDDDCCA.',
      '..ACCCDDDDCCCA..',
      '...AACCCCCCAA...',
      '.....AAAAAA.....',
      '......ABBA......',
      '....AAABBAAA....',
      '....AAAAAAAA....',
      '................',
      '................',
    ],
  ),

  edr: s(
    { A: '#155e75', B: '#22d3ee', C: '#67e8f9', D: '#083344' },
    [
      '...CC......CC...',
      '..CDDC....CDDC..',
      '..CDDC....CDDC..',
      '...CC......CC...',
      '.....A....A.....',
      '......AAAA......',
      '.....ABBBBA.....',
      '.....ABBBBA.....',
      '......AAAA......',
      '.....A....A.....',
      '...CC......CC...',
      '..CDDC....CDDC..',
      '..CDDC....CDDC..',
      '...CC......CC...',
      '................',
      '................',
    ],
  ),
};
